---
- name: Configure HAProxy and Keepalived
  hosts: loadbalancers
  become: yes
  tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist
        cache_valid_time: 3600

    - name: Install HAProxy and Keepalived
      apt:
        name:
          - haproxy
          - keepalived
          - curl
        state: present

    - name: Enable IP forwarding
      sysctl:
        name: "{{ item }}"
        value: '1'
        state: present
        reload: yes
      loop:
        - net.ipv4.ip_forward
        - net.ipv4.ip_nonlocal_bind

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        backup: yes
      notify: restart haproxy

    - name: Configure Keepalived
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        backup: yes
      notify: restart keepalived

    - name: Configure firewall for load balancers
      ufw:
        rule: allow
        port: "{{ item }}"
      loop:
        - '80'
        - '443'
        - '8404'
        - '112'
        - '22'

    - name: Allow VRRP between load balancers
      ufw:
        rule: allow
        from_ip: "{{ item }}"
      loop: "{{ groups['loadbalancers'] }}"

    - name: Enable firewall
      ufw:
        state: enabled
        policy: deny

    - name: Start and enable HAProxy
      systemd:
        name: haproxy
        state: started
        enabled: yes

    - name: Start and enable Keepalived
      systemd:
        name: keepalived
        state: started
        enabled: yes

  handlers:
    - name: restart haproxy
      systemd:
        name: haproxy
        state: restarted

    - name: restart keepalived
      systemd:
        name: keepalived
        state: restarted