all:
  children:
    loadbalancers:
      hosts:
        lb1:
          ansible_host: 192.168.1.101
          keepalived_priority: 110
          keepalived_state: MASTER
        lb2:
          ansible_host: 192.168.1.102
          keepalived_priority: 100
          keepalived_state: BACKUP
    webservers:
      hosts:
        web1:
          ansible_host: 192.168.1.201
          server_id: 1
        web2:
          ansible_host: 192.168.1.202
          server_id: 2
        web3:
          ansible_host: 192.168.1.203